name: Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'

jobs:
  ubuntu:
    name: ${{ matrix.ubuntu_image }}
    runs-on: ${{ matrix.ubuntu_image }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_image: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y gperf
      - name: Configure
        run: cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -DCMAKE_INSTALL_PREFIX=install -Bbuild -Sdependencies
      - name: Build
        run: cmake --build build
